# Copyright (c) 2026 GUIHO Technologies as represented by Cristóvão GUIHO
# All Rights Reserved.

# Create the trigger on Google Cloud Build UI and then came back here
# https://console.cloud.google.com/cloud-build/triggers


# step - bun|npm|yarn install
# step - bun|npm|yarn test
# step - bun|npm|yarn build
# step - bun|npm|yarn stage #test-build
# step - bun|npm|yarn publish
